/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.Month;
import java.time.Year;
import java.util.*;
import java.time.LocalDate;
import java.sql.*;
import java.sql.Date;

/**
 *
 * @author Laptop
 */
public class PlayerData extends javax.swing.JPanel {

    /**
     * Creates new form PlayerDat
     */
    public PlayerData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        genderButtons = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        labelUsername = new java.awt.Label();
        txtUsername = new java.awt.TextField();
        labelYob = new java.awt.Label();
        labelMob = new java.awt.Label();
        labelGender = new java.awt.Label();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        insertButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        SpinnerNumberModel monthModel = new SpinnerNumberModel(
            1, 1, 12, 1
        );
        monthSpinner = new javax.swing.JSpinner();
        int currentYear = java.time.Year.now().getValue();
        SpinnerNumberModel model = new SpinnerNumberModel(2000, currentYear - 120, currentYear, 1);
        yearSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 199));
        setPreferredSize(new java.awt.Dimension(533, 488));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelUsername.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(51, 51, 51));
        labelUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        labelYob.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        labelYob.setForeground(new java.awt.Color(51, 51, 51));
        labelYob.setText("Year of Birth");

        labelMob.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        labelMob.setForeground(new java.awt.Color(51, 51, 51));
        labelMob.setText("Month of Birth");

        labelGender.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        labelGender.setForeground(new java.awt.Color(51, 51, 51));
        labelGender.setText("Gender");

        genderButtons.add(maleButton);
        maleButton.setForeground(new java.awt.Color(51, 51, 51));
        maleButton.setSelected(true);
        maleButton.setText("Male");

        genderButtons.add(femaleButton);
        femaleButton.setForeground(new java.awt.Color(51, 51, 51));
        femaleButton.setText("Female");

        insertButton.setBackground(new java.awt.Color(153, 255, 153));
        insertButton.setForeground(new java.awt.Color(0, 0, 0));
        insertButton.setText("Insert");
        insertButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(153, 255, 153));
        editButton.setForeground(new java.awt.Color(0, 0, 0));
        editButton.setText("Edit");
        editButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(153, 255, 153));
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Delete");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        monthSpinner.setModel(monthModel);

        yearSpinner.setModel(model);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelYob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(maleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(femaleButton))
                    .addComponent(monthSpinner)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(insertButton))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelYob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(editButton)))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleButton)
                        .addComponent(femaleButton)
                        .addComponent(deleteButton)))
                .addContainerGap())
        );

        playerTable.setBackground(new java.awt.Color(204, 255, 204));
        playerTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        playerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "username", "date_of_birth", "gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        playerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(playerTable);
        loadPlayers();

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Player Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        

    public boolean insertPlayer(String username, Date dob, String gender) {

        String query = "INSERT INTO Player(username, date_of_birth, gender) "
                + "Values(?, ?, ?)";

        try(Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query)){

            ps.setString(1, username);
            ps.setDate(2, dob);
            ps.setString(3, gender);

            return ps.executeUpdate() > 0; // TRUE if it worked

        } catch (SQLException e){
            e.printStackTrace();
            return false;
        }
    }
    
    public void loadPlayers() {
        String query = "SELECT * FROM Player ORDER BY username";

        try(Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery()) {

            // Get metadata for column names
            ResultSetMetaData meta = rs.getMetaData();
            int columnCount = meta.getColumnCount();
            String[] columnNames = new String[columnCount];
            for (int i = 0; i < columnCount; i++) {
                columnNames[i] = meta.getColumnName(i + 1);
            }

            // Create table model
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            // Populate rows
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 0; i < columnCount; i++) {
                    rowData[i] = rs.getObject(i + 1); // get data by column index
                }
                model.addRow(rowData);
            }

            // Set model to JTable
            playerTable.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             

        // Get values of username, dob, and gender
        String username = txtUsername.getText();
        int year = (Integer) yearSpinner.getValue();
        int month = (Integer) monthSpinner.getValue();
        LocalDate dob = LocalDate.of(year, month, 1);
        java.sql.Date sqlDob = java.sql.Date.valueOf(dob);
        String gender = (maleButton.isSelected()) ? "M" : "F";

        if(username == null)
            return;

        String query = "INSERT INTO Player(username, date_of_birth, gender) "
        + "VALUES(?, ?, ?)";

        boolean isSuccessful = insertPlayer(username, sqlDob, gender);
        if(isSuccessful) {
            JOptionPane.showMessageDialog(this, "Player added successfully.");
            loadPlayers();
        } else {
            JOptionPane.showMessageDialog(this, "");
        }
    }                                            

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int id = Integer.parseInt(playerTable.getValueAt(playerTable.getSelectedRow(), 0).toString());
        if(id == -1)
            return;

        String username = txtUsername.getText();
        int year = (Integer) yearSpinner.getValue();
        int month = (Integer) monthSpinner.getValue();
        LocalDate dob = LocalDate.of(year, month, 1);
        java.sql.Date sqlDob = java.sql.Date.valueOf(dob);
        String gender = (maleButton.isSelected()) ? "M" : "F";

        String query = "UPDATE Player SET username = ?, date_of_birth = ?, "
            + "gender = ? WHERE id = ?";

        try(Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query)) {

            ps.setString(1, username);
            ps.setDate(2, sqlDob);
            ps.setString(3, gender);
            ps.setInt(4, id);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Player successfully updated.");
            loadPlayers();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    null,
                    "SQL Error: " + e.getMessage()
            );
        }
    }                                          

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int id = Integer.parseInt(playerTable.getValueAt(playerTable.getSelectedRow(), 0).toString());
        if(id == -1)
            return;
        
        String query = "DELETE FROM Player WHERE id = ?";

        try(Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query)) {

            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Player successfully deleted.");
            loadPlayers();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    null,
                    "SQL Error: " + e.getMessage()
            );
        }
        
        
    }                                            

    private void playerTableMouseClicked(java.awt.event.MouseEvent evt) {                                         
        int id = Integer.parseInt(playerTable.getValueAt(playerTable.getSelectedRow(), 0).toString());
        if(id == -1)
            return;

        String query = "SELECT * FROM Player WHERE id = " + id;

        try(Connection con = DBConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery(query)) {
            while(rs.next()) {
                txtUsername.setText(rs.getString("Username"));

                LocalDate sqlDate = rs.getDate("date_of_birth").toLocalDate();
                yearSpinner.setValue(sqlDate.getYear());
                monthSpinner.setValue(sqlDate.getMonthValue());

                if(Objects.equals(rs.getString("gender"), "M")) {
                    maleButton.setSelected(true);
                } else {
                    femaleButton.setSelected(true);
                }
            }

        } catch(SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    null,
                    "SQL Error: " + e.getMessage()
            );
        }

    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.ButtonGroup genderButtons;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labelGender;
    private java.awt.Label labelMob;
    private java.awt.Label labelUsername;
    private java.awt.Label labelYob;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JSpinner monthSpinner;
    private javax.swing.JTable playerTable;
    private java.awt.TextField txtUsername;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration                   
}
